# Generated by Django 4.2.1 on 2023-05-19 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposalreview",
            name="proposal",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.proposal",
            ),
            preserve_default=False,
        ),
    ]
