# Generated by Django 4.2.1 on 2023-05-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_proposal_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="class_field",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="number_of_students",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="section",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="semester",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
