# Generated by Django 4.2.1 on 2023-05-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_proposal_class_field_proposal_number_of_students_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="comments",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="status",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
