# Generated by Django 4.2.1 on 2023-05-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_proposal_comments_proposal_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=models.CharField(default="pending", max_length=250),
        ),
    ]
