# Generated by Django 4.2.1 on 2023-05-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_proposal_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_pic",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
