# Generated by Django 4.2.1 on 2023-05-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_student_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="presentation",
            field=models.DateTimeField(null=True),
        ),
    ]
