# Generated by Django 4.2.1 on 2023-05-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_proposal_presentation"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="student_names",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="student_rolls",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="student_sections",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
